"""empty message

Revision ID: 748eadce3f92
Revises: ea556551a91b
Create Date: 2026-05-13 15:49:26.008933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748eadce3f92'
down_revision = 'ea556551a91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_entry', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_exit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_sym', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('entry_journal', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_entry')
    op.drop_table('entry')
    op.drop_table('user')
    # ### end Alembic commands ###
