"""empty message

Revision ID: c222cf43a5aa
Revises: d9692609d87f
Create Date: 2026-05-09 08:34:01.225454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c222cf43a5aa'
down_revision = 'd9692609d87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
